# Generated by Django 5.2.17 on 2026-08-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=128)),
                ("policy_version", models.CharField(max_length=32)),
                ("user_id", models.CharField(blank=True, max_length=64)),
                ("organization_id", models.CharField(blank=True, max_length=64)),
                ("client_id", models.CharField(blank=True, max_length=64)),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField()),
                ("duration_ms", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=32)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("serialized_bytes", models.PositiveIntegerField(default=0)),
                ("truncated", models.BooleanField(default=False)),
                ("request_digest", models.CharField(max_length=64)),
                ("filter_fields", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
